In [ ]:
#Problem Statement 1:
##Write a function so that the columns of the output matrix are powers of
#the input vector.
#The order of the powers is determined by the increasing boolean argument. 
#Specifically,when increasing is False, the i-th output column is the 
#input vector raised element-wise to the power of N - i - 1.

#HINT: Such a matrix with a geometric progression in each row is named 
#for Alexandre- Theophile Vandermonde.
#x = np.array([1, 2, 3, 4,5])
#len(x)
#y = np.vander(x, increasing = False)
#y

In [3]:
  

import numpy as np 
def van (a,n,inc): # function for Vander progression
   if inc == 'True': 
       i = n-1
       while i >= 0:
           a[:,n-i-1]**=(n-i-1)
           i -=1
       return a
   else:
       i = n-1
       k= 1
       while i >=0:
           a[:,n-i-1]**= (n-k)
           i -=1
           k = k + 1
       return a
num = [1,2,3,4,5]
print ('Input list of numbers is: ', num)
length = len (num) # count of inputs in the list
length
in_arr = np.array(num).reshape(length,1)
in_arr # converted to array
zer_arr = np.zeros((length,length)) # square matrix of zeroes
zer_arr
com_arr = zer_arr + in_arr
com_arr # Matrix of 5,5 

inc_param = input('Select parameter for increasing (True/False): ',)
inc_param 
alex_vander = van (com_arr,length,inc_param)
print('\nAlex Vandermonde matrix with parameter as',inc_param, 'is \n', alex_vander)


Input list of numbers is:  [1, 2, 3, 4, 5]
Select parameter for increasing (True/False): True

Alex Vandermonde matrix with parameter as True is 
 [[  1.   1.   1.   1.   1.]
 [  1.   2.   4.   8.  16.]
 [  1.   3.   9.  27.  81.]
 [  1.   4.  16.  64. 256.]
 [  1.   5.  25. 125. 625.]]


In [ ]:
Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [2]:
import numpy as np
x = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
N = 2
np.vander(x, N)

array([[  3,   1],
       [  5,   1],
       [  7,   1],
       [  2,   1],
       [  8,   1],
       [ 10,   1],
       [ 11,   1],
       [ 65,   1],
       [ 72,   1],
       [ 81,   1],
       [ 99,   1],
       [100,   1],
       [150,   1]])